### ISSUE TITLE
Example 1 uses Lock-Volume instead of Lock-BitLocker

### ISSUE THREAD

**Issue by zzzz4** [MicrosoftDocs/windows-powershell-docs#1042]
PS C:\> Lock-Volume -MountPoint "E:" -ForceDismount
should read
 PS C:\> Lock-BitLocker -MountPoint "E:" -ForceDismount
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d5601e-74dc-d528-1c19-8b0738fee2f6
* Version Independent ID: 012a8322-ddf8-fda3-5a3d-4c2f0d570503
* Content: [Lock-BitLocker (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/lock-bitlocker?view=win10-ps)
* Content Source: [docset/windows/bitlocker/lock-bitlocker.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/lock-bitlocker.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @- 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by e0i** [comment]
@zzzz4 

In our investigation it has been found that the issue has been addressed with the following commit:

[[e5f5651 ] Change Lock-Volume to Lock-BitLocker ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/e5f565162a6da5bab25c2eeeac6b8d45255aab6b)

We are thus closing this issue since it seems to be resolved. 

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
