### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by imamkhaira** [MicrosoftDocs/windows-powershell-docs#1163]
Typo in https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmremotefx3dvideoadapter?view=win10-ps#description

it should be RemoteFX, not RemovteFX

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by msbemba** [comment]
@imamkhaira Thank you for your feedback. I was not able to identify the typo in the document. Either it was already fixed or I'm looking at the wrong doc. Can you check and confirm if the URL for the doc is correct https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmremotefx3dvideoadapter?view=win10-ps#description ?

**Comment by e0i** [comment]
Hello, @imamkhaira 

It seem the issue had already been addressed with the following commit,

[[e840853 ] typo: Removte -&gt; Remote ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/e840853eb71dd8a49c8116a535f917d1eef74bcb)

Changes can also be observed [live](https://docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmremotefx3dvideoadapter?view=win10-ps#description).

We are thus closing this issue since it seems to be resolved. 

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
