### ISSUE TITLE
-WhatIf parameter does not follow documented behavior

### ISSUE THREAD

**Issue by amaiman** [MicrosoftDocs/windows-powershell-docs#1231]
This documentation states that using the -WhatIf parameter will result in: "The cmdlet is not run."
This is not the observed behavior. The parameter is ignored and the command is executed (which causes test commands to actually change the environment.)

(I'm aware this is supposed to be for documentation issues, not bugs, but technically the documentation is wrong since it doesn't match reality. The Microsoft maintainer of this document should be able to pass this on to the relevant product team.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78c61a26-4692-8228-9b1d-a2319cac1709
* Version Independent ID: bd1a3a35-9e2a-25c3-7387-d72fd31f4231
* Content: [New-SmbShare (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=win10-ps)
* Content Source: [docset/windows/smbshare/new-smbshare.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/new-smbshare.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@amaiman 

The issue has been noted and the document will be revised in the light of your feedback.

Thank you.

**Comment by msbemba** [comment]
@amaiman Thank you for the feedback. -what if command is not supposed to execute the cmdlet. I'll see what I can do to let the product team know about this.

Thanks
Sri

**Comment by e0i** [comment]
Hello, @amaiman

The issue has been reproduced and verified as a bug and is being escalated to product team for investigation.

The issue is thus being closed because the issues section of this repository is intended for product documentation problems, not product support.

Should you have any similar inquiries or problems, please consider consulting [PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) or [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community).

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
