### ISSUE TITLE
Add-PhysicalDisk does NOT honor '-whatif' Option

### ISSUE THREAD

**Issue by Beta-Tester99** [MicrosoftDocs/windows-powershell-docs#1237]
Add-PhysicalDisk does NOT honor '-whatif' Option

in testing using this command, the -whatif option was not honored.

can be quite dangerous in production environments.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @Beta-Tester99 

The issue is under investigation and you will be notified with any changes on the way.

Thank you for providing feedback.

**Comment by e0i** [comment]
Similar: #1231

**Comment by e0i** [comment]
Hello, @Beta-Tester99 

Just like the similar issue, #1231, this issue as well has been reproduced and verified as a bug and is being escalated to product team for investigation.

The issue is thus being closed because the issues section of this repository is intended for product documentation problems, not product support.

Should you have any similar inquiries or problems, please consider consulting [PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell) or [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community).

Also feel free to reply if there is anything else that could be done to improve the document itself.

Thanks.
