### ISSUE TITLE
Documentation of -confirm parameter is wrong

### ISSUE THREAD

**Issue by fbehrens** [MicrosoftDocs/windows-powershell-docs#1330]
The current behaviour of the command is:
* Without `-confirm` or with `-confirm:$false` one is asked for confirmation.
* With `-confirm:$true` confirmation is not asked for.

Please adjust documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216a4b07-b99d-9b0e-2784-f0a501e83c3e
* Version Independent ID: b692b387-8334-3ad7-4144-eb9daafe1040
* Content: [Remove-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/remove-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/addsadministration/remove-aduser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello, @fbehrens 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by velkovb** [comment]
@fbehrens Hi,
Thanks you for trying to make MicrosoftDocs a better place. I was not able to replicate your issue.
```
[DC01]: PS C:\> Remove-ADUser Test

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove" on target "CN=Test,CN=Users,DC=home,DC=lab".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"): n
[DC01]: PS C:\> Remove-ADUser Test -Confirm

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove" on target "CN=Test,CN=Users,DC=home,DC=lab".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"): n

[DC01]: PS C:\> Remove-ADUser Test -Confirm:$true

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove" on target "CN=Test,CN=Users,DC=home,DC=lab".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"): n

[DC01]: PS C:\> Remove-ADUser Test -Confirm:$false
```
Only when Confirm is explicitly specified as $false you will not be asked for confirmation. By default switch parameters are always false. unless explicitly specified - [Switch Parameters](https://docs.microsoft.com/powershell/developer/cmdlet/types-of-cmdlet-parameters#switch-parameters). Here you are not prompted because of the -Confirm parameter but because the impact of the cmdlet is High. You could read more about cmdlet confirm impact and preference - [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)

Let me know if you have any questions.

**Comment by e0i** [comment]
Hello @fbehrens,

The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.

Thanks.
