### ISSUE TITLE
Add-AppxProvisionedPackage: Missing help for -Regions parameter

### ISSUE THREAD

**Issue by ChadMcCaffery** [MicrosoftDocs/windows-powershell-docs#1735]
### Background

I was reading the topic, "[Preinstall Apps Using DISM](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/preinstall-apps-using-dism)", which has the following text:

> Starting with Windows 10, version 1803, apps can be preinstalled without being pinned to the Start Menu when you use DISM /add-provisionedappxpackage with the /region option. When you preinstall an app, you can choose to leave the app out of your LayoutModification.xml and the app will successfully install without appearing as a Start Menu tile. When a list of regions is NOT specified, the app will be provisioned only if it is pinned to start layout.

I use the DISM module in PowerShell, so I looked-up `Add-AppxProvisionedPackage` for more info on `-Regions` parameter, but there isn't any. I specifically want to know if it supports `-Regions all`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678cf8fb-4a65-3660-c818-b17e1490b703
* Version Independent ID: c7670040-daad-57f2-3dad-453210dcf35e
* Content: [Add-AppxProvisionedPackage (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=win10-ps&redirectedfrom=MSDN&source=docs)
* Content Source: [docset/windows/dism/Add-AppxProvisionedPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dism/Add-AppxProvisionedPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
