### ISSUE TITLE
-Filter parameter is a String, not a ScriptBlock

### ISSUE THREAD

**Issue by AikenBM** [MicrosoftDocs/windows-powershell-docs#180]
The `-Filter` parameter is described here with Backus-Naur form stating that it should be enclosed in curly braces.  However, that causes issues because something enclosed by curly braces in PowerShell is a ScriptBlock literal, yet the `-Filter` parameter actually accepts a value of type String.  This data type mismatch will cause problems with variable expansion and is, simply put, inherently less robust than using a String.  It's very easy to mistakenly create a ScriptBlock filter which does not expand correctly.

For a simple example taken from StackOverflow <https://stackoverflow.com/a/44184818>, these work:

    Get-ADUser -Filter "sAMAccountName -eq ""$SamAc"""
    Get-ADUser -Filter "sAMAccountName -eq `"$SamAc`""
    Get-ADUser -Filter "sAMAccountName -eq '$SamAc'"
    Get-ADUser -Filter ('sAMAccountName -eq "' + $SamAc + '"')

This also works:

    Get-ADUser -Filter { SamAccountName -eq $SamAC }

But these do not:

    Get-ADUser -Filter { SamAccountName -eq "$SamAC" }
    Get-ADUser -Filter { SamAccountName -eq '$SamAC' }

This will also fail:

    $User = [PSCustomObject]@{ SamAccountName = $SamAC }
    Get-ADUser -Filter { SamAccountName -eq $User.SamAccountName }

This will work:

    $User = [PSCustomObject]@{ SamAccountName = $SamAC }
    Get-ADUser -Filter "SamAccountName -eq '$($User.SamAccountName)'"

Even worse, many of these "fail" states for the ScriptBlock literal will result in comparisons that will either always be true or always be false and will not throw terminating errors.  Indeed, they will silently succeed! That means you won't realize that your script is either filtering everything or filtering nothing regardless of your input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0b9f4db-305b-847a-1ab6-ad3b547a91f7
* Version Independent ID: a626e689-b2ba-6a11-c17b-9f1fd0e565cd
* Content: [Get-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/get-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/get-aduser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/get-aduser.md)
* Service: **unspecified**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by AikenBM** [comment]
Interestingly, while this fails with the error "Get-ADUser : Property: 'SamAccountName' not found in object of type: 'System.Management.Automation.PSCustomObject'.":

```
$User = [PSCustomObject]@{ SamAccountName = $SamAC }
Get-ADUser -Filter { SamAccountName -eq $User.SamAccountName }
```

This works:

```
$User = Get-ADUser -Identity $SamAC
Get-ADUser -Filter { SamAccountName -eq $User.SamAccountName }
```

So, however the filter described in `about_ActiveDirectory_Filter` works, it clearly doesn't work like PowerShell's parser.

**Comment by jszabo98** [comment]
This works for me:

```
$User = [PSCustomObject]@{ SamAccountName = $SamAC }
Get-ADUser -Filter "SamAccountName -eq '$($User.SamAccountName)'"
```

**Comment by jszabo98** [comment]
Note that using a script block in this case will not work:

`Get-ADUser -Filter {SamAccountName -eq "$($User.SamAccountName)"}`

**Comment by jszabo98** [comment]
Please correct example 4:


```powershell
PS C:\> Get-ADUser -Filter 'Name -eq "ChewDavid"' -SearchBase "DC=AppNC" -Properties "mail" -Server lds.Fabrikam.com:50000
```

**Comment by MaratMussabekov** [comment]
Hello, @AikenBM could you please review [PR 752](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/752/files), whether it makes the situation clear?

@jszabo98 , I think the example 4 is ok, as value (ChewDavid) is not a variable, both curly braces and quotes are works correctly. What do you think?

Thank you

**Comment by jszabo98** [comment]
@MaratMussabekov I personally think example 4's filter should be a string, since that is the type, instead of depending on a script block being casted to a string.  Otherwise this teaches people to use something that won't work in all cases.  Quoting in filters seem to be a trial an error kind of thing.  For example, variables don't need to be quoted at all inside a single quoted filter:
```powershell
get-aduser -filter 'name -like $user'
```
By the way, a "not null" example would be nice to include:
```powershell
get-aduser -filter 'accountlockouttime -notlike "*"'
```
Or a "not member of" (parentheses seem to be optional, but normally required outside of filters).  -neq won't work since memberof is an array.
```powershell
get-aduser -filter '-not (memberof -eq "foo")'
```

**Comment by MaratMussabekov** [comment]
** Otherwise this teaches people to use something that won't work in all cases.**
Dear @jszabo98 , I do not think that using curly braces is somehow incorrect: both curly braces and quotes works, as long as PowerShell syntax is correct. More details here [Filters with PowerShell Active Directory Module Cmdlets](https://social.technet.microsoft.com/wiki/contents/articles/28485.filters-with-powershell-active-directory-module-cmdlets.aspx)

About adding more examples: article is not dedicated to filtering, it is about Get-ADUser commandlet. 
For filtering, there are some other articles:
1. [Filters with PowerShell Active Directory Module Cmdlets](https://social.technet.microsoft.com/wiki/contents/articles/28485.filters-with-powershell-active-directory-module-cmdlets.aspx)
2. [about_ActiveDirectory_Filter](https://docs.microsoft.com/previous-versions/windows/server/hh531527(v=ws.10))

**Comment by jszabo98** [comment]
Just because something is in the documentation, doesn't mean it's correct.  :)

**Comment by e0i** [comment]
@officedocsbot close

**Comment by jszabo98** [comment]
The  Backus-Naur form in the docs for -filter is wrong, and should be removed.  -Filter is a string, not a scriptblock.
