### ISSUE TITLE
A guide about how to set parameters such as managedRuntimeVersion on New-WebAppPool

### ISSUE THREAD

**Issue by atwayne** [MicrosoftDocs/windows-powershell-docs#1812]
Is it possible to add an example or link about how to set parameters on the application pool created? It's very likely people need to do this if they are trying to create an application pool.
For example, `managedRuntimeVersion`, `autoStart` etc..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a01808e-fcdb-8533-0047-6906fd13db39
* Version Independent ID: 203ea1cb-1ca4-ed9a-78cf-1ea1d593e6de
* Content: [New-WebAppPool (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webapppool?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/winserver2012-ps/webadminstration/New-WebAppPool.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@atwayne Hello Wayne,

Thank you for your feedback.

I believe that the reason the information you are suggesting is missing form the article is because it is not done via this cmdlet. The only official MS document I was able to find is the following one which I believe could be useful in this case:
[PowerShell Snap-in: Making Configuration Changes to Websites and App Pools](https://docs.microsoft.com/iis/manage/powershell/powershell-snap-in-making-simple-configuration-changes-to-web-sites-and-application-pools).

I would add that and an example on how to set the properties you have mentioned.

**Comment by atwayne** [comment]
@velkovb That's awesome ;) Thanks
