### ISSUE TITLE
bits and bytes

### ISSUE THREAD

**Issue by the-gangster** [MicrosoftDocs/windows-powershell-docs#1874]
quite confusing but maybe a result of changing parameter "-ThrottleRateActionBytesPerSecond" (in older documentation) to "-ThrottleRateActionBitsPerSecond" :
While the description says this will set the rates to the according bits per second, the output in the examples where the parameter is used (2,4+6) returns a value of bytes per second. 
e.g. example 2:
command: ... -ThrottleRateActionBitsPerSecond 1MB
output: ...ThrottleRate   : 1 MBytes/sec
description: ...throttles the traffic at 1,000,000 bits per second

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e2530c-1643-f7ad-fcf4-ce1a975e9d2f
* Version Independent ID: a8036c5e-fcc6-c319-9108-5e79bb883cd7
* Content: [New-NetQosPolicy (netqos)](https://docs.microsoft.com/en-us/powershell/module/netqos/new-netqospolicy?view=win10-ps#feedback)
* Content Source: [docset/windows/netqos/New-NetQosPolicy.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netqos/New-NetQosPolicy.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by the-gangster** [comment]
Similar happened in **set**-netqospolicy in example 4.
"-ThrottleRateActionBitsPerSecond 3000KB"
gets explained with 
"sets a new throttling rate at 3,000,000 bytes per second"

**Comment by e0i** [comment]
The content has been revised accordingly. Thank you for the feedback.

**Comment by AlmightyLks** [comment]
@e0i Asking for this to be revised again, as it is still faulty, it seems?

There is an inconsistency between winserver2012 and winserver2012r2 (and above), as 2012 states `ThrottleRateActionBytesPerSecond`, and 2012r2 states `ThrottleRateActionBitsPerSecond`. I'm going to assume, that's because it is, in fact, different, and wasn't left as a mistake.

Then, however, the description of the examples don't make sense.

| Server | CLI-Output | Description | Note |
| ------------- | ------------- | ------------- | ------------- |
| winserver2012  | 1.049 M**Bits**/sec  | 1,000,000 **bytes** per second  | CLI-Parameter states "Action**Bytes**PerSecond" |

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/9cadf9876b6d87daddffc0b906bce092138edbf9/docset/winserver2012-ps/netqos/New-NetQosPolicy.md?plain=1#L132-L143

---

The following errors are also present in the other docs:
| Server | CLI-Output | Description | Note |
| ------------- | ------------- | ------------- | ------------- |
| winserver2012r2  | 1.049 M**Bits**/sec  | 1,000,000 **bytes** per second  | 1Mbit does not equate 1 Million Bytes |
| winserver2016  | 1.049 M**Bits**/sec  | 8,000,000 **bytes** per second  | Conversion error, 1Mbit does not equate 1 Million Bytes |
| winserver2019  | 1.049 M**Bits**/sec  | 8,000,000 **bytes** per second  | Conversion error, 1Mbit does not equate 1 Million Bytes |
| winserver2022  | 1.049 M**Bits**/sec  | 8,000,000 **bytes** per second  | Conversion error, 1Mbit does not equate 1 Million Bytes |

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/9cadf9876b6d87daddffc0b906bce092138edbf9/docset/winserver2012r2-ps/netqos/New-NetQosPolicy.md?plain=1#L143-L154
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/9cadf9876b6d87daddffc0b906bce092138edbf9/docset/winserver2016-ps/netqos/New-NetQosPolicy.md?plain=1#L144-L155
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/9cadf9876b6d87daddffc0b906bce092138edbf9/docset/winserver2019-ps/netqos/New-NetQosPolicy.md?plain=1#L144-L155
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/9cadf9876b6d87daddffc0b906bce092138edbf9/docset/winserver2022-ps/netqos/New-NetQosPolicy.md?plain=1#L144-L155

---

# Mind!
I only showed an example and comparisons between "Example 2".  
This mistake persists multiple times in multiple examples, however.
