### ISSUE TITLE
Examples use `-Confirm` as boolean, but it is a switch

### ISSUE THREAD

**Issue by evilensky** [MicrosoftDocs/windows-powershell-docs#1891]
Correct syntax would be `-Confirm:$false` , etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf1abaf-c268-b76f-48b5-5f5723fecb83
* Version Independent ID: 0c17d9d3-bbc4-f467-b44c-d78bb0c7e370
* Content: [Set-SmbServerConfiguration (smbshare)](https://docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps#feedback)
* Content Source: [docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/smbshare/Set-SmbServerConfiguration.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
@evilensky Switch parameters are a common source of confusion among readers. Please let me know whether the following discussion thread from a similar issue answers your question,

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1891

Thank you.

**Comment by evilensky** [comment]
I appreciate that but any examples using spaces are broken on Server 2016.

```
PS C:\Windows\system32> Set-SmbServerConfiguration -AnnounceServer $False -Confirm $False
Set-SmbServerConfiguration : A positional parameter cannot be found that accepts argument 'False'.
At line:1 char:1
+ Set-SmbServerConfiguration -AnnounceServer $False -Confirm $False
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SmbServerConfiguration], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Set-SmbServerConfiguration
```

**Comment by evilensky** [comment]
@e0i I believe your link is back to this issue and not to the similar issue.

**Comment by e0i** [comment]
That should be a copy-paste error. Find below links issues with relevant discussion:

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1463
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1330
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1395

**Comment by evilensky** [comment]
Those are very useful and they have expanded my understanding of how Switch parameters and impacts are implemented.  I am reporting not confusion about the behavior but how the examples are formated.  In #1395 this [comment](https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1395#issuecomment-546901871) is exactly what I describe in this issue:

>I don't think you get the switch parameters :) You probably confuse them with boolean.
You cannot pass a value to the switch parameter. A switch parameter is false if not specified and true only if it is specified (if you include -Confirm in the command line) . So when you specify it in the command that makes it true. You can only override this behaviour with a slightly different syntax - "-Confirm:$false".

The examples seem to try to pass boolean to `-Confirm'.  Here is example 2:

```
Set-SmbServerConfiguration -RequireSecuritySignature $True -EnableSecuritySignature $True -EncryptData $True -confirm $False
```

**Comment by AikenBM** [comment]
I agree that the example is *at best* oddly written and is almost certainly incorrect. The documentation needs to be corrected either way. If the example in the documentation is specifying `-confirm $false` to explicitly disable confirmation,  *then it is incorrect* because that syntax is wrong.

Here is what example 3 currently says:

    Set-SmbServerConfiguration -RequireSecuritySignature $True -EnableSecuritySignature $True -EncryptData $True -confirm $False

If the goal is to explicitly disable confirmation, this is what it *should* say:

    Set-SmbServerConfiguration -RequireSecuritySignature $True -EnableSecuritySignature $True -EncryptData $True -confirm:$False

The incorrect example ends with `-confirm $False`, but the `-confirm` parameter is a switch. That means what `-confirm $False` is actually *two parameters*. It's like passing one parameter `-confirm:$true` and a second unnamed parameter `$False`, which may be assigned to another parameter in the bound parameter list or might end up as an unbound parameter or argument.

Take this test function:

```
function Test-Parameter {
    param(
        [String]$String1,
        [Switch]$Switch1,
        [Bool]$Bool1
    )

    process {
        'Bound Parameters:'
        $PSBoundParameters
        ''
        'Positional Parameters:'
        for ($i = 0; $i -lt $args.Count; $i++) {
            'Arg {0}: {1}' -f $i, $args[$i]
        }
    }
  }
```

Now try it out and see what the behavior is:

```
PS C:\> Test-Parameter -Bool1 $true -String1 'asdf' -Switch1:$false
Bound Parameters:

Key     Value
---     -----
Bool1    True
String1  asdf
Switch1 False

Positional Parameters:

PS C:\> Test-Parameter -Bool1 $true -String1 'asdf' -Switch1 $false
Bound Parameters:

Key     Value
---     -----
Bool1    True
String1  asdf
Switch1  True

Positional Parameters:
Arg 0: False

PS C:\> Test-Parameter -Bool1 $true -Switch1 $false
Bound Parameters:

Key     Value
---     -----
Bool1    True
Switch1  True
String1 False

Positional Parameters:
```

That last one is *real* bad, because the `$false` got assigned to the `-String1` parameter *which wasn't even specified in the command* because it's [the first named parameter that wasn't explicitly named](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-7#positional-parameters). 

Presumably, then, the example documentation will actually function as though you specified this:

```
Set-SmbServerConfiguration -RequireSecuritySignature $True -EnableSecuritySignature $True -EncryptData $True -confirm -AnnounceComment $False
```

`AnnounceComment`, being the first unspecified named parameter, will probably be assigned the value of the first positional parameter.
