### ISSUE TITLE
No Download or OS information 

### ISSUE THREAD

**Issue by RandyDotCom** [MicrosoftDocs/windows-powershell-docs#1911]
[Enter feedback here]
Can't download the module, which should be built in. 
Can tell what OS Versions this applys too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abd96a6f-4148-6fef-f1d3-471681d27806
* Version Independent ID: 1aed4a27-e8ce-1715-17ad-a8914eb5f3c6
* Content: [UpdateServices](https://docs.microsoft.com/en-us/powershell/module/updateservices/?view=win10-ps)
* Content Source: [docset/windows/updateservices/UpdateServices.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/updateservices/UpdateServices.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by MaratMussabekov** [comment]
Hello,
**Can't download the module, which should be built in** - no need for separate download, it could be enabled by adding  "API and PowerShell cmdlets" under "Windows Server Update Services Tools" in windows server features. See [here](https://www.powershellmagazine.com/2012/11/07/client-and-patch-management-using-the-updateservices-module/)
**Can tell what OS Versions this applys too.** - all server versions since WS2012
