### ISSUE TITLE
add monthly variable

### ISSUE THREAD

**Issue by aaronsssya** [MicrosoftDocs/windows-powershell-docs#1929]
We have a job which will triggered on the every first of month. Due to gMSA requirement, we have to perform the PowerShell to create tasks. Therefore, we might need monthly option.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ce19ed-65a3-a416-73ff-3388c0503647
* Version Independent ID: c2af9c57-b677-e836-1c60-595fcc64bb14
* Content: [New-ScheduledTaskTrigger (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasktrigger?view=win10-ps#feedback)
* Content Source: [docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/scheduledtasks/New-ScheduledTaskTrigger.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by e0i** [comment]
Hello,

The issues section of this repository is intended for documentation and content related issues.

Please consider sending your input via the Feedback Hub so that it gets addressed via the proper channels:

[Send Feedback via PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

Thank you.
