### ISSUE TITLE
Documented default value for -Confirm incorrect for Move-ADDirectoryServerOperationMasterRole 

### ISSUE THREAD

**Issue by fshields** [MicrosoftDocs/windows-powershell-docs#2018]
Move-ADDirectoryServerOperationMasterRole behaves as if the "-Confirm" switch defaults to True. Without specifying that switch, I am prompted to confirm the move of each FSMO role type.

However, the documentation incorrectly states that the default value for this switch is False.  This should be updated.

_Additional improvements:_

- Change the description from "Prompts you for confirmation before running the cmdlet." to "Prompts you for confirmation of each chosen FSMO role before executing a move. Override this behavior by specifying `-Confirm:$false`. (useful for scripts)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001745f8-db7f-53ce-444a-e0a45b590ef9
* Version Independent ID: 7520d272-a7f0-438d-76a6-710d9cb7af82
* Content: [Move-ADDirectoryServerOperationMasterRole (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/move-addirectoryserveroperationmasterrole?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Move-ADDirectoryServerOperationMasterRole.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Move-ADDirectoryServerOperationMasterRole.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by RAJU2529** [comment]
@e0i . Assign user to look into this issue

**Comment by velkovb** [comment]
@fshields Hello,

Thank you for trying to make MicrosoftDocs a better place.

By default switch parameters are always false. unless explicitly specified - [Switch Parameters](https://docs.microsoft.com/powershell/developer/cmdlet/types-of-cmdlet-parameters#switch-parameters). Here you are not prompted because of the -Confirm parameter but because the impact of the cmdlet is High. You could read more about cmdlet confirm impact and preference - [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)

Let me know if you have any questions.
