### ISSUE TITLE
Remove-ADUser -Confirm parameter notes

### ISSUE THREAD

**Issue by mpietihsm** [MicrosoftDocs/windows-powershell-docs#2052]
I think it's kind of silly that the very important notes about the -Confirm parameter for Remove-ADUser are listed in the "Notes" section at the bottom of the page and not in the parameter's own section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216a4b07-b99d-9b0e-2784-f0a501e83c3e
* Version Independent ID: b692b387-8334-3ad7-4144-eb9daafe1040
* Content: [Remove-ADUser (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-aduser?view=win10-ps)
* Content Source: [docset/windows/addsadministration/Remove-ADUser.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/Remove-ADUser.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by velkovb** [comment]
@mpietihsm Hello,

Thank you for trying to make MicrosoftDocs a better place. Unfortunately, I would say this note is actually incorrect as the **Confirm** parameter is not set by default. By definition all switch parameters are false unless explicitly listed. The reason you are prompted for confirmation is because the cmdlet is defined with High impact and your **$ConfirmPreference** variable is set to High. You can read more about this topic here: [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)
