### ISSUE TITLE
Documentation seems to lack important information on output object properties

### ISSUE THREAD

**Issue by rkuiper1** [MicrosoftDocs/windows-powershell-docs#2069]
Hi,

In my search for what 'IsPublishedToUser' realy means (the currently logged on user? or any user?) I found that the output of Get-AppvClientPackage is not described at all. There is a mentioning of 'Microsoft.AppV.AppvClientPowerShell.AppvClientPackage', but there's nothing to be found on this topic as well.

The same goes for UserPending and GlobalPending... What is pending? Is it removal, publishing, unpublishing or something else?

Would it be a good idea to elaborate on the output object properties?

Cheers,
Richard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63f75703-a40f-73df-3a98-56ade6932af7
* Version Independent ID: 99f27eaf-fc65-3570-3260-8261c8fd1fb2
* Content: [Get-AppvClientPackage (appvclient)](https://docs.microsoft.com/en-us/powershell/module/appvclient/get-appvclientpackage?view=win10-ps)
* Content Source: [docset/windows/appvclient/Get-AppvClientPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appvclient/Get-AppvClientPackage.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

**Comment by sowjanya365** [comment]
Hi @rkuiper1 

Thank you for reaching out! 

In this context, the output and input sections refers to the Object of "AppvClientPackage".

And with regards to your other queries related to "IsPublishedToUser" and "UserPending and GlobalPending", not sure if you are referring these on the same page or different one. We do not find these wordings on the document. Could you please help us navigating to the right page, so that we can better assist you in clarifying these to you.

Look forward to you response. Thank you so much!
