### ISSUE TITLE
BitLocker docs missing BackupToAAD-BitLockerKeyProtector

### ISSUE THREAD

**Issue by fjarlq** [MicrosoftDocs/windows-powershell-docs#2185]
The [BitLocker documentation](https://docs.microsoft.com/en-us/powershell/module/bitlocker/)  covers every function in the BitLocker module except `BackupToAAD-BitLockerKeyProtector`.

There is some coverage of it in these docs:
- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises
- https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-and-adds-faq

**Comment by mardahl** [comment]
It would be great to get some documentation on which version of Windows 10 support this cmdlet and some examples.
I had to write a wrapper script, because it was erroring out, even though it actually worked, so some more details would be nice. T
https://github.com/mardahl/PSBucket/blob/master/Invoke-EscrowBitlockerToAAD.ps1

**Comment by fjarlq** [comment]
I see that this issue has been fixed:
https://docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector
