### ISSUE TITLE
Default value of confirm switch is true for Enable-ClusterStorageSpacesDirect 

### ISSUE THREAD

**Issue by asengutt** [MicrosoftDocs/windows-powershell-docs#2223]
This is just minor typo or probably changed somewhere down the timeline.
Confirmation is requested by default on this command.
Hence Confirm switch default should be noted as true in documentation.

PS C:\> Enable-ClusterStorageSpacesDirect –CimSession Quest
 
**Confirm
Are you sure you want to perform this action?
Quest: Performing operation 'Enable Cluster Storage Spaces Direct' on Target 'Quest'.
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c44898fe-aecd-4acb-6de2-79606805e36c
* Version Independent ID: 1967653d-ebb8-7a06-af67-8359e8a85bdd
* Content: [Enable-ClusterStorageSpacesDirect (FailoverClusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/enable-clusterstoragespacesdirect?view=win10-ps)
* Content Source: [docset/windows/failoverclusters/Enable-ClusterStorageSpacesDirect.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/Enable-ClusterStorageSpacesDirect.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by velkovb** [comment]
Hi @asengutt ,

Thank you for trying to make MicrosoftDocs a better place.

By default switch parameters are always false. unless explicitly specified - [Switch Parameters](https://docs.microsoft.com/powershell/scripting/developer/cmdlet/types-of-cmdlet-parameters?view=powershell-5.1#switch-parameters). Here you are not prompted because of the -Confirm parameter but because the impact of the cmdlet is High. You could read more about cmdlet confirm impact and preference - [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)

Furthermore, you could check the following article to understand confirmation requests - https://docs.microsoft.com/powershell/developer/cmdlet/users-requesting-confirmation

Let me know if you have any questions.
