### ISSUE TITLE
PowerShell 7.1.0 error using this command

### ISSUE THREAD

**Issue by DeadUnicorn1352** [MicrosoftDocs/windows-powershell-docs#2248]
Hello, i've encountered with a problem using Powershell 7.1.0
When using Get-WinUserLanguageList command you get an error :
Get-WinUserLanguageList: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination.
![изображение](https://user-images.githubusercontent.com/74927006/102717490-55d98a80-42eb-11eb-9c73-fe3255ffe1a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3d9b94-9f70-6c11-552d-a6f00f20fec8
* Version Independent ID: 0603585f-7db5-8ccf-99ca-beef7cf671b4
* Content: [Get-WinUserLanguageList (International)](https://docs.microsoft.com/en-us/powershell/module/international/get-winuserlanguagelist?view=win10-ps)
* Content Source: [docset/windows/international/Get-WinUserLanguageList.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/Get-WinUserLanguageList.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
The feedback section you have submitted this feedback from is intended for product documentation issue.

Please consider checking with PowerShell community for your problem so that it gets resolved.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks.
