### ISSUE TITLE
PowerShell Copy-UserInternationalSettingsToSystem cmdlet missing from International module

### ISSUE THREAD

**Issue by SCCMAdmin** [MicrosoftDocs/windows-powershell-docs#2272]
Hi Team, this documentation shows a cmdlet called Copy-UserInternationalSettingsToSystem which appears to do something I am after for some automation. However this cmdlet is not in the International module (2.0.0.0) on Windows 10 1909. I have posted about the issue here [https://docs.microsoft.com/en-us/answers/questions/230112/powershell-copy-userinternationalsettingstosystem.html](url).

So either this documentation is ahead of its time and doesn't match what is in Windows or PowerShell is not keeping up with itself. Please review and let me know what you have found.

In spending some hours looking around on this today, I only found 1 other post in uservoice area (1 vote) for someone saying the cmdlet was missing (sorry can't find that link now, but I think that is in the wrong place potentially).

Thanks heaps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7004729a-2d93-6c6f-6b80-6411bc97aabb
* Version Independent ID: 98f3eb92-4777-ef78-aa79-35b40b964631
* Content: [Copy-UserInternationalSettingsToSystem (International)](https://docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=win10-ps)
* Content Source: [docset/windows/international/Copy-UserInternationalSettingsToSystem.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/international/Copy-UserInternationalSettingsToSystem.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @erik0686
* Microsoft Alias: **ertorres**

**Comment by SCCMAdmin** [comment]
The link again which didn't work in original post:
[https://docs.microsoft.com/en-us/answers/questions/230112/powershell-copy-userinternationalsettingstosystem.html](url)

What's news here after near 3 weeks? 

Considering calling Premier support next so I can carry on with my work.

Thanks.

**Comment by jfdoyon** [comment]
I second this issue ... The command is documented by appears to be missing, and I could certainly use it.

In the mean time do we know of an alternative to this command that might do the same thing?

**Comment by SCCMAdmin** [comment]
So it appears Microsoft has now removed the web page (sub page to International module) where this command would be.
https://docs.microsoft.com/en-us/powershell/module/international/?view=win10-ps

So that means we have no command and no documentation any longer. Aligned yes, good start. Why was the page removed?
More importantly, when will this command be available?

**Comment by jfdoyon** [comment]
I'm trying to set a number of "international" settings for machines being deployed via Autopilot. The OOBE options are limited, so some other means must be used. Technically it appears the International PowerShell commands could work, *if* that copy command existed and worked. Since it doesn't, I've reverted to using control.exe intl.cpl,,/f:somexmlfile.xml ... it works, but is an outdated approach that may eventually die once the control panel fully disappears, so hopefully it'll be sorted out before then!

**Comment by e0i** [comment]
Hello, It seems that the documentation too has been removed from the repository along with the command itself.

Since the article does not exist in the repository, the best course of action might be to consult [Feedback Hub](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10) for this problem. 

Thanks.
