### ISSUE TITLE
updte PS 

### ISSUE THREAD

**Issue by farhan-githubksa** [MicrosoftDocs/windows-powershell-docs#2341]
How to resolve this issue? please guide.

Update-Help: Failed to update Help for the module(s) 'PSReadline, WindowsUpdateProvider' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
Update-Help: Failed to update Help for the module(s) 'HgsClient, HgsDiagnostics' with UI culture(s) {en-US} : A Help URI cannot contain more than 10 redirections. Specify a valid Help URI..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

**Comment by sdwheeler** [comment]
These are known issues that have already been reported many times. We are in the process of fixing these issues but it will be a few months before we can implement the final fix. 

For PSReadLine, the problem will be fixed in the next release of Windows, however, existing versions will continue to have this problem. We posted a workaround to fix this on the PowerShell blog. See the following posts.

- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/
- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/
