### ISSUE TITLE
Not able to install ppkg on windows server 2016 using powershell

### ISSUE THREAD

**Issue by abhinavhcl** [MicrosoftDocs/windows-powershell-docs#2383]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a150b4f4-290b-32c6-9633-d358dd3efaac
* Version Independent ID: 76ba113d-f32d-058d-f7a2-7c8daadba900
* Content: [Install-ProvisioningPackage (provisioning)](https://docs.microsoft.com/en-us/powershell/module/provisioning/install-provisioningpackage?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/provisioning/Install-ProvisioningPackage.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/provisioning/Install-ProvisioningPackage.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

**Comment by e0i** [comment]
@abhinavhcl 

Note that the feedback section you have submitted this feedback from is intended for product documentation issues.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks.
