### ISSUE TITLE
Silent removal does not work

### ISSUE THREAD

**Issue by gabrielgt** [MicrosoftDocs/windows-powershell-docs#2512]
The -Confirm parameter does not work. The command ask for confirmation whether you put it on or not. The only way I found to avoid the confirmation is with -Confirm:$false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62e48887-984b-9df7-893a-8f11b2ec8a7e
* Version Independent ID: 542878a5-9211-fc68-6ee6-1a88949b5a0f
* Content: [Remove-IISSiteBinding (IISAdministration)](https://docs.microsoft.com/en-us/powershell/module/iisadministration/remove-iissitebinding?view=windowsserver2019-ps)
* Content Source: [docset/winserver2019-ps/iisadministration/Remove-IISSiteBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2019-ps/iisadministration/Remove-IISSiteBinding.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by velkovb** [comment]
Hi @gabrielgt,

Thank you for trying to make MicrosoftDocs a better place.

By default switch parameters are always false. unless explicitly specified - [Switch Parameters](https://docs.microsoft.com/powershell/scripting/developer/cmdlet/types-of-cmdlet-parameters?view=powershell-5.1#switch-parameters). Here you are not prompted because of the -Confirm parameter but because the impact of the cmdlet is High. You could read more about cmdlet confirm impact and preference - [$ConfirmPreference](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables#$ConfirmPreference), [ConfirmImpact](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_functions_cmdletbindingattribute#confirmimpact)

Furthermore, you could check the following article to understand confirmation requests - [users-requesting-confirmation](https://docs.microsoft.com/powershell/developer/cmdlet/users-requesting-confirmation)

Let me know if you have any questions.

**Comment by gabrielgt** [comment]
Thank you for the explanation @velkovb
