### ISSUE TITLE
Looks good but errors

### ISSUE THREAD

**Issue by 62Hank** [MicrosoftDocs/windows-powershell-docs#254]
I keep getting asked what port.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7fe5aca-0d89-a75b-56e0-68abfa11e846
* Version Independent ID: 36b16f53-b0b5-fe6d-e819-b4778ecf8035
* Content: [Invoke-WsusServerCleanup (wsus)](https://docs.microsoft.com/en-us/powershell/module/wsus/invoke-wsusservercleanup?view=win10-ps)
* Content Source: [docset/windows/wsus/invoke-wsusservercleanup.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/wsus/invoke-wsusservercleanup.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by e0i** [comment]
Hello, @62Hank  thank you for providing feedback.

Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.

**Comment by e0i** [comment]
@officedocsbot close
