### ISSUE TITLE
Get-MpComputerStatus Properties Page no longer updated

### ISSUE THREAD

**Issue by PhiZ-9** [MicrosoftDocs/windows-powershell-docs#3712]
On the [Get-MpComputerStatus PowerShell Reference Page](https://learn.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus), there is a link to the properties of the MSFT_MpComputerStatus class at the bottom:

https://learn.microsoft.com/en-us/previous-versions/windows/desktop/defender/msft-mpcomputerstatus#properties

This link redirects to an article from 2018. Is there any current documentation available on the MSFT_MpComputerStatus class (or its equivalent)? I am searching for an explanation on new properties like the `InitializationProgress` field from Get-MpComputerStatus that was added in Platform 4.18.23110.3.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b1d3d6-3f25-abb8-3d58-dd3481203100
* Version Independent ID: 192ecac7-fbc7-24e4-43c7-163550e211fa
* Content: [Get-MpComputerStatus (Defender)](https://learn.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2022-ps)
* Content Source: [docset/winserver2022-ps/defender/Get-MpComputerStatus.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2022-ps/defender/Get-MpComputerStatus.md)
* Product: **w10**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by PhiZ-9** [comment]
Dear @scanum, 

the issue is still not completed, because the documentation is still very outdated.
It would be quite nice to know the current status and features of this command (at least newer than 2018).

Could you or the team please have a look at this documentation?
