### ISSUE TITLE
Dead link to 

### ISSUE THREAD

**Issue by eabase** [MicrosoftDocs/windows-powershell-docs#3718]
### Prerequisites

- [X] **Existing Issue:** Search the existing issues for this repository. If there is an issue that fits your needs do not file a new one. Subscribe, react, or comment on that issue instead.
- [X] **Descriptive Title:** Write the title for this issue as a short synopsis. If possible, provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
- [X] **Verify Version:** If there is a mismatch between documentation and the behavior on your system, ensure that the version you are using is the same as the documentation. Check this box if they match or the issue you are reporting is not version specific.

### Links

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2019-ps/windowsupdate/WindowsUpdate.md
https://aka.ms/winsvr-2019-pshelp

### Summary

Dead link to pages in:
* https://github.com/MicrosoftDocs/windows-powershell-docs/blob/main/docset/winserver2019-ps/windowsupdate/WindowsUpdate.md

This breaks `Update-Help -UICulture en-US -Module WindowsUpdate` for this.

**Comment by tiburd** [comment]
Thanks for taking the time to submit feedback about our content. We’ve implemented a new system to make it easier for you to provide feedback. As a result, we’re no longer accepting feedback in this repository via GitHub Issues so this issue is being closed. For more information about the new system, please visit [https://learn.microsoft.com/office/new-feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Foffice%2Fnew-feedback&data=05%7C02%7Cv-tibur%40microsoft.com%7C109c1f9f64aa497ebaf208dbfaade688%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638379397110902359%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HSLFHHpohWIWvNS0jgGFFFvN37yDeGmYvgBu1q2hVXQ%3D&reserved=0).
