### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by incaweber** [MicrosoftDocs/windows-powershell-docs#449]
For the optional parameter '-Confirm' the default value is documented as '$False'. Where in reality it's default value ist '$True'.
The 'Notes' even state the following:
"By default, this cmdlet has the Confirm parameter set, which prompts you to confirm before a removal of the specified object type can occur. To bypass prompting for confirmation before removal, you can specify -Confirm:$False when using this cmdlet."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7016ebc2-6472-8242-c1f6-04657ee9e0b9
* Version Independent ID: d53a52b7-110c-e5af-a7ec-d5767a3c4259
* Content: [Remove-ADGroupMember (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/remove-adgroupmember?view=win10-ps)
* Content Source: [docset/windows/addsadministration/remove-adgroupmember.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/remove-adgroupmember.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@incaweber 

It seems that this issue has already been addressed with the following commit.

[[e166f78 ] Update remove-adgroupmember.md ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/e166f783d361af44451a7314f2216e775d9e47a9#diff-ae58daa25988405d2abbbc5fcb481ad0)

We are thus closing this issue since it seems to be resolved. Feel free to re-open it if you feel it hasn't been resolved.

Thank you for taking the time to provide feedback.

**Comment by e0i** [comment]
@officedocsbot close
