### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by woodsr83** [MicrosoftDocs/windows-powershell-docs#454]
Get-NetAdapterPowerManagementSettings has a property for AllowComputerToTurnOffDevice.  However, it's not an option to set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db188483-c397-64c2-4a23-4e3a3de8d57e
* Version Independent ID: bf70ee5b-efaa-5873-fbbf-d38a2f6c273c
* Content: [Set-NetAdapterPowerManagement (netadapter)](https://docs.microsoft.com/en-us/powershell/module/netadapter/set-netadapterpowermanagement?view=win10-ps)
* Content Source: [docset/windows/netadapter/set-netadapterpowermanagement.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netadapter/set-netadapterpowermanagement.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by ojrb** [comment]
Hi @e0i  reviewing the document and the comment, this document that is referenced by the issue is about the PS command **Set-NetAdapterPowerManagement**, the comment indicate that the property  **r AllowComputerToTurnOffDevice** can not be set for the PS command **Get-NetAdapterPowerManagementSettings** but this command Does not exists, the correct one is **Get-NetAdapterPowerManagement**.  The comment reference other command that not exist in the original Document. The only error I found in the Document was that the links to the commands in the bottom are broken ! how can I proceed with this issue?

**Comment by ojrb** [comment]
Hi @e0i  The PR #1030 solve this issue ! please review and merge !

**Comment by e0i** [comment]
@woodsr83 

In our investigation it has been found that the document needs no updates as there is not a note for each parameter that cannot be changed, and that "each switch that is not settable outside of the switch properties should not be pointed out."

Please consider consulting PowerShell UserVoice channel regarding your product feedback via the following link,

[PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

You may also check relevant resources and ask the community for any other inquiries via PowerShell Community,

[PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
