### ISSUE TITLE
Disable-AdfsDeviceRegistration is obsolete

### ISSUE THREAD

**Issue by desmondkung** [MicrosoftDocs/windows-powershell-docs#463]
Running Disable-AdfsDeviceRegistration on Windows Server 2016 throws up the following: "WARNING: The command 'Disable-AdfsDeviceRegistration' is obsolete. The Cmdlet has been deprecated. Go to
http://go.microsoft.com/fwlink/?LinkID=259190 for additional details."

How are we able to determine whether ADFS Device Registration has been disabled on the server?

**Comment by e0i** [comment]
Hello, @desmondkung 

Somehow your issue has been opened without being associated to a documentation topic.

Could you clarify which documentation you're referring to? A link would be helpful.

Thanks.

**Comment by desmondkung** [comment]
Hi @e0i 
It's been a while for this this. I don't really remember but my guess would be something to do with ADFS Device Registration based on the content of the comment?

**Comment by e0i** [comment]
Hello, @desmondkung 

Based on the provided information, we could not identify which documentation this issue might be associated with.

Note that the feedback section you have used to submit this issue is intended for product documentation issues only.

Thus, please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.

[Windows 10 Support](https://support.microsoft.com/en-us/hub/4338813/windows-help?os=windows-10)

Thank you for following up.

**Comment by e0i** [comment]
@officedocsbot close
