### ISSUE TITLE
Doesn't actually work.

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/windows-powershell-docs#476]
Gives cryptic error "Parent node has no children of type application".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5703c562-b00d-0da3-661b-7a2a27bad250
* Version Independent ID: bfd9bf90-f873-ed2a-a9a8-068ecbff7ae7
* Content: [New-WebApplication (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webapplication?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebApplication.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebApplication.md)
* Product: **w10**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by ScottEDubya** [comment]
Seeing this as well. not sure if it's my fault or not... i've successfully run the script on my local machine, but when attempting to run this in our build environment it gives me the above error. will report back if i figure out why

**Comment by ScottEDubya** [comment]
This happened when i gave an app pool name or website that didn't exist. not sure which one, but in my case both were wrong

**Comment by e0i** [comment]
Hello, @Pxtl Thank you for providing feedback.

Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.

**Comment by e0i** [comment]
@officedocsbot close
