### ISSUE TITLE
SAML Consumer Endpoints for a Relying Party Trust instance

### ISSUE THREAD

**Issue by ChrisFors** [MicrosoftDocs/windows-powershell-docs#497]
Currently I see that SAML Consumer Endpoints for a Relying Party Trust instance can be created via PowerShell and can subsequently be viewed in the GUI.  How can we view these via PowerShell?  These aren't shown by the Get-ADFSRelyingPartyTrust command and I can't find where it is documented how to do this.

C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25d7e0b7-398b-fcb5-cd62-7190fd2692c9
* Version Independent ID: b030b833-324e-5bea-b675-f459bb31b6d5
* Content: [Get-AdfsRelyingPartyTrust (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/get-adfsrelyingpartytrust?view=win10-ps)
* Content Source: [docset/windows/adfs/get-adfsrelyingpartytrust.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/get-adfsrelyingpartytrust.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
Hello, @ChrisFors  thank you for providing feedback.

Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.

**Comment by e0i** [comment]
@officedocsbot close
