### ISSUE TITLE
Can I use this for private use?

### ISSUE THREAD

**Issue by hoksource** [MicrosoftDocs/windows-powershell-docs#515]
It says self-signed certificate for testing purposes. But I am going to use it just for encrypting files from my machine to save in the cloud and be read by another private machine that I also own.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80b6f8a-6227-63cb-391f-bd3324a57251
* Version Independent ID: e3ce9f6c-ae5f-9b4b-2d3b-d709e886c01c
* Content: [New-SelfSignedCertificate (pkiclient)](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps)
* Content Source: [docset/windows/pkiclient/new-selfsignedcertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/pkiclient/new-selfsignedcertificate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
For personal use, where you set up the self-signed cert as trusted, then it should work just fine.

As ever, best practice is to use a 'real' cert - but you situation may not warrant the cost.

**Comment by e0i** [comment]
Hello @hoksource ,

We are closing this issue since your support question seems to be answered by the community.

Note that this issue section is for product documentation issues only. For any similar problems that you encounter, feel free to seek advice via [PowerShell Community](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

Thank you for providing feedback.

**Comment by e0i** [comment]
@officedocsbot close
