### ISSUE TITLE
DisableIntrustionPreventionSystem does not work

### ISSUE THREAD

**Issue by dmonagha** [MicrosoftDocs/windows-powershell-docs#741]
In the following docs:
https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps

[-DisableIntrusionPreventionSystem <Boolean>]

This cmdlet is not actually working. Whether invoked manually via Powershell or through DSC, the cmdlet returns $True without actually changing the Properties of Windows Defender.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @dmonagha  thank you for providing feedback.

Note that the feedback section you have submitted this feedback from is intended for product documentation issues only.

Please consider checking with PowerShell community for your problem so that it gets resolved quickly.

[PowerShell Community Links](https://docs.microsoft.com/powershell/#pivot=main&panel=community)

For bug reports specific to PowerShell, please visit, [PowerShell at GitHub](https://github.com/powershell/powershell/issues/).

Thanks again.

**Comment by e0i** [comment]
@officedocsbot close
