### ISSUE TITLE
This is called Microsoft "Docs"?? It's a shame!

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#758]
Good evening

If a PowerShell-Function can be seriously described as documentation, then - of course - it is mandatory to describe the created object and its properties.

This "docs" here could almost be created by a generator using reflection.

It's a shame that M$$ demands many billions and offer this "quality" for fundamental PowerShell cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edbe7a00-ff80-0a0e-77fe-fcc7f2e50b7b
* Version Independent ID: bc8a398f-6479-fa2c-7094-55f9e973586c
* Content: [Get-VHD (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/get-vhd?view=win10-ps)
* Content Source: [docset/windows/hyper-v/get-vhd.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/get-vhd.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
Hello, @schittli 

The content is being reviewed in the light of your feedback and we'll keep you posted on updates.

Thank you for providing feedback.

**Comment by sowjanya365** [comment]
Hi @schittli 

Good Evening!

Thank you so much for your valuable contribution. Really appreciate it!

Kindly help us to understand what exactly need to be added/modified on this documentation. We will definitely consider your feedback and make the necessary changes. Looking forward to your response. Thank you.

**Comment by e0i** [comment]
@schittli 

It seems that the requested changes have been applied to the document via the following commit:

[ [977d20] Updated output data types ](https://github.com/MicrosoftDocs/windows-powershell-docs/commit/977d201fb0a6961e68139ce7847d3422c183e54f)

You may preview the updated document through the following link since the updates will take time to be published live:

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/get-vhd.md

Please clarify whether that answers your feedback.

Thank you.

**Comment by e0i** [comment]
@officedocsbot close
