### ISSUE TITLE
"Docs" means "Documentation". Therefore: what exactly is a "saved state"?

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windows-powershell-docs#908]
It's really annoying that we have to ask M$ the most basic questions like thise one:
what is a "Saved State" in Hyper-V?
If a VM is powered off, why does it has a saved state?
Do Checkpoints have a saved state - and why?

Yes, real Docs would be very useful for commercial and expensive products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbab0860-02f7-dffc-44cd-a1617378fae8
* Version Independent ID: 5af5d587-766e-c069-5d61-df74fe4dd0de
* Content: [Remove-VMSavedState (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/remove-vmsavedstate?view=win10-ps)
* Content Source: [docset/windows/hyper-v/remove-vmsavedstate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/remove-vmsavedstate.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by velkovb** [comment]
@schittli Hi Tom,

Thank you for trying to make MicrosoftDocs better place.

Saving the state of a Virtual Machine is similiar to hibernating a physical computer. The contents of the memory is written do disk - [Save-VM](https://docs.microsoft.com/en-us/powershell/module/hyper-v/Save-VM?view=win10-ps). 
Regarding the Checkpoints, if you make a checkpoint on a running VM it will have saved state because it is running and it will save the memory as well. If the VM is not running when you make the checkpoint, there will be no saved state because there is no active memory.

Let me know if this answers your questions.

**Comment by e0i** [comment]
Hello @schittli  ,

We are closing this issue since your question seems to be answered. Feel free to re-open this issue if you still feel it hasn't been answered.

Thanks.

**Comment by e0i** [comment]
@officedocsbot close
